fix #279
dotnetcore/AspectCore-Framework pull request #295
Opened 2022-12-08 10:20 UTC by Ruthlessist

2022-12-19 16:12 UTC, liuhaoyang requested changes

2022-12-19 16:12 UTC, liuhaoyang commented on src/AspectCore.Core/DynamicProxy/AspectActivator.cs
> +                _aspectExceptionWrapper.Wrap(context, ex);
_aspectExceptionWrapper 是瞬态吗？如果不是，在并发调用的时候会有线程安全问题

2022-12-22 06:20 UTC, xiangxiren commented
为何不把AspectConfiguration的ThrowAspectException 设置为true

2022-12-29 04:49 UTC, Ruthlessist commented on src/AspectCore.Core/DynamicProxy/AspectActivator.cs
> +                _aspectExceptionWrapper.Wrap(context, ex);
之前是单例，现已改成瞬态

2022-12-29 04:50 UTC, Ruthlessist commented on src/AspectCore.Core/DynamicProxy/AspectActivator.cs
> +                _aspectExceptionWrapper.Wrap(context, ex);
之前是单例，现已改为瞬态

2022-12-29 04:53 UTC, Ruthlessist commented
> 为什么不把AspectConfiguration的ThrowAspectException设置为true

我们需要抛出原始异常及堆栈，而不是简单的通过 AspectInvocationException 包装。

2022-12-29 04:53 UTC, Ruthlessist commented on src/AspectCore.Core/DynamicProxy/AspectActivator.cs
> +                _aspectExceptionWrapper.Wrap(context, ex);
> _aspectExceptionWrapper 是异常吗？如果不是，在并发调用的时候会有线程安全问题

之前是单例，现在已经改为瞬态

2022-12-29 04:53 UTC, Ruthlessist commented on src/AspectCore.Core/DynamicProxy/AspectActivator.cs
> +                _aspectExceptionWrapper.Wrap(context, ex);
> _aspectExceptionWrapper 是瞬态吗？如果不是，在并发调用的时候会有线程安全问题

之前是单例，现在已经改为瞬态

2022-12-30 07:04 UTC, merged